"""Generate the conceptual data schema, and the picture of it that the documents show.

The diagram is built from :data:`multimodal_etl.schema.FIELDS` (the single source of
truth), so code, documentation and schema always stay aligned. It writes ``docs/data_schema.mmd``
then, when ``mmdc`` (mermaid-cli, through npx) is available, renders it to
``docs/images/data_schema.png`` and records that rendering in ``docs/images/MANIFEST.json``
beside the screenshots — same directory, same manifest, one place to look for the provenance
of any published image.

The model is **conceptual** — business entities and relations, not physical storage. It
makes the role of every field explicit and shows the text-image link visually.

Usage:
    uv run python scripts/build_schema_diagram.py
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
from datetime import UTC, datetime
from pathlib import Path

from multimodal_etl.schema import ENTITIES, fields_of
from multimodal_etl.utils.paths import DOCS_DIR, IMAGES_DIR, ROOT_DIR

SOURCE = "scripts/build_schema_diagram.py"
MANIFEST = IMAGES_DIR / "MANIFEST.json"

# Which field belongs to which entity comes straight from multimodal_etl.schema: adding a
# field to the schema makes it appear in the diagram without touching anything here.

# Conceptual relations (Mermaid cardinalities).
RELATIONS: tuple[tuple[str, str, str, str], ...] = (
    ("SOURCE", "||--o{", "PUBLICATION", "publishes"),
    ("PUBLICATION", "||--||", "TEXT_CONTENT", "carries"),
    ("PUBLICATION", "||--||", "IMAGE_CONTENT", "pairs"),
    ("PUBLICATION", "||--o|", "LABEL", "annotates"),
)


def _mermaid_type(dtype: str) -> str:
    """Translate a logical type into one the diagram can display."""
    mapping = {
        "string": "string",
        "integer": "int",
        "boolean": "bool",
        "datetime": "datetime",
    }
    return mapping.get(dtype, dtype)


def _key(entity: str, name: str) -> str:
    """Say whether a field is a primary or a foreign key within its entity."""
    if entity == "PUBLICATION" and name == "id":
        return "PK"
    if entity == "PUBLICATION" and name == "source_id":
        return "FK"
    if entity == "SOURCE" and name == "source_id":
        return "PK"
    # The content entities share the key of the publication they describe.
    if name == "id":
        return "PK"
    return ""


def build_mermaid() -> str:
    """Build the Mermaid text of the conceptual schema."""
    lines = ["erDiagram"]

    # Relations.
    for left, cardinality, right, label in RELATIONS:
        lines.append(f"    {left} {cardinality} {right} : {label}")
    lines.append("")

    # Entities and attributes (type + role + key).
    for entity in ENTITIES:
        lines.append(f"    {entity} {{")
        # The join key is repeated on each content entity.
        if entity in {"TEXT_CONTENT", "IMAGE_CONTENT", "LABEL"}:
            lines.append('        string id PK "KEY"')
        if entity == "SOURCE":
            lines.append('        string source_id PK "KEY"')
        for spec in fields_of(entity):
            lines.append(
                f"        {_mermaid_type(spec.dtype)} {spec.name} "
                f'{_key(entity, spec.name)} "{spec.role}"'
            )
        lines.append("    }")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _git(*arguments: str) -> str:
    done = subprocess.run(
        ["git", *arguments], cwd=ROOT_DIR, capture_output=True, text=True, check=False
    )
    return done.stdout.strip()


def declare(image: Path) -> None:
    """Record what this rendering is, next to the screenshots and in the same file.

    A picture with no manifest entry cannot be regenerated by whoever finds it: nobody knows
    which tool drew it, from what, or when. One PDF of this same diagram sat in ``docs/`` for
    exactly that reason — a third rendering of one file, reachable from no document.
    """
    payload: dict = {"schema": "image-manifest/1", "images": {}}
    if MANIFEST.exists():
        payload = json.loads(MANIFEST.read_text(encoding="utf-8"))
    payload.setdefault("schema", "image-manifest/1")
    payload.setdefault("images", {})
    payload["images"][image.name] = {
        "sha256": hashlib.sha256(image.read_bytes()).hexdigest(),
        "written": datetime.now(tz=UTC).date().isoformat(),
        "source": SOURCE,
        "command": "uv run python scripts/build_schema_diagram.py",
        "rendered_from": "docs/data_schema.mmd",
        "renderer": "mermaid-cli, white background, neutral theme",
        "demonstrates_behaviour": (
            "the entities, their cardinalities and the role of every field are drawn from "
            "multimodal_etl.schema, so a field added to the code appears in this picture "
            "without anyone editing it"
        ),
        "data_source": "none: the diagram is generated from the schema module",
        "git_revision": _git("rev-parse", "HEAD"),
        "depends_on": ["src/multimodal_etl/schema.py", SOURCE],
    }
    payload["images"] = dict(sorted(payload["images"].items()))
    MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8", newline=""
    )
    print(f"[ok] manifest entry written: {image.name}")


def render(mmd_path: Path) -> Path | None:
    """Render the .mmd as a PNG through mmdc, when the tool is available.

    One rendering and not three. The PNG is what every document shows; the PDF that used to
    be written beside it was a second copy of the same picture that no document linked to.
    """
    mmdc = shutil.which("mmdc") or shutil.which("mmdc.cmd")
    npx = shutil.which("npx") or shutil.which("npx.cmd")
    if mmdc:
        base_command = [mmdc]
    elif npx:
        base_command = [npx, "-y", "@mermaid-js/mermaid-cli"]
    else:
        print("[warn] neither mmdc nor npx available: rendering skipped, the .mmd still stands.")
        return None

    IMAGES_DIR.mkdir(parents=True, exist_ok=True)
    output = IMAGES_DIR / "data_schema.png"
    try:
        subprocess.run(
            [*base_command, "-i", str(mmd_path), "-o", str(output),
             "-b", "white", "-t", "neutral"],
            check=True,
            capture_output=True,
            text=True,
        )
    except (subprocess.CalledProcessError, FileNotFoundError) as exc:
        print(f"[warn] rendering failed ({exc}). The .mmd still stands.")
        return None
    print(f"[ok] rendering written: {output.name}")
    return output


def main(argv: list[str] | None = None) -> int:
    """Generate the .mmd, then its rendering, then the manifest entry of that rendering."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--no-render",
        action="store_true",
        help="write the .mmd only — mermaid-cli draws a different PNG from one version to "
        "the next, and scripts/smoke.py compares what it regenerates byte for byte",
    )
    arguments = parser.parse_args(argv)

    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    mmd_path = DOCS_DIR / "data_schema.mmd"
    mmd_path.write_text(build_mermaid(), encoding="utf-8", newline="")
    print(f"[ok] Mermaid schema written: {mmd_path}")
    if arguments.no_render:
        return 0
    image = render(mmd_path)
    if image is not None:
        declare(image)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
