"""Run this project end to end, and write down that it ran.

A repository whose continuous integration is frozen says nothing about itself: the green tick
is two years old, or absent. What replaces it is ``reports/run-evidence.json`` — the exact
command, the day, the revision, the tool versions, what it cost, and the tracked files it
produced. A reader can rerun that command and compare.

**The run must reproduce what the repository publishes.** The steps below regenerate the key
outputs; if any of them comes out different from the committed version, no evidence is
written and the differing files are named. That is the whole value of the exercise: evidence
that merely says « it ran » proves that something ran, not that what is published is what it
produces.

    uv run python scripts/smoke.py

Run it on a clean clone, before the release tag. No workflow writes this file: a committed
artefact regenerated by continuous integration is an artefact whose author is a machine
nobody watches.
"""

from __future__ import annotations

import json
import os
import platform
import shutil
import subprocess
import sys
import tempfile
import time
from datetime import UTC, datetime
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path

from multimodal_etl.utils.paths import ROOT_DIR, SCRIPTS_DIR

EVIDENCE = "reports/run-evidence.json"
COMMAND = "uv run python scripts/smoke.py"

#: The tracked files this run regenerates. Each one is compared with its committed version:
#: a smoke test that writes nothing proves that the process starts, not that it works.
KEY_OUTPUT: tuple[str, ...] = (
    # The corpus is not among them, and cannot be: a collection assembled from live feeds is
    # never twice the same. What survives a comparison is everything downstream of one
    # measurement, which is the schema the code derives and the report rendered from the
    # numbers that run wrote down.
    "docs/data_schema.mmd",
    "reports/data_quality.md",
)

#: The distributions whose version changes the result. Not the whole lock file — the reader
#: needs what would explain a different number, not an inventory.
TOOLS: tuple[str, ...] = ("pandas", "pyarrow", "sqlalchemy", "feedparser", "pillow", "requests")

#: Where the smoke run writes its own corpus: a temporary directory, removed when it is over.
#:
#: Not `var/`, and the reason is worth the line. On a workstation whose checkout sits on a
#: virtual sync drive — Google Drive, OneDrive — SQLite loses tables between two connections
#: of the same engine: the load writes `publication`, then fails to find `source`. The
#: corpus, the images and the database this script builds are throwaway state, so they go
#: where the operating system puts throwaway state.

#: The source the smoke runs against: the one whose input is versioned in this repository.
#: The three RSS feeds and the two downloads bring back something different every day, which
#: is exactly what a run meant to be compared must not do.
SMOKE_SOURCE = "kaggle_fakeddit"


def _run(*arguments: str, environment: dict[str, str] | None = None) -> None:
    """Run one of this repository's own scripts, and fail loudly if it does not finish."""
    print(f"[run] {' '.join(arguments)}")
    done = subprocess.run(
        [sys.executable, *arguments],
        cwd=ROOT_DIR,
        env={**os.environ, "PYTHONIOENCODING": "utf-8", **(environment or {})},
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        check=False,
    )
    print(done.stdout.rstrip())
    if done.returncode != 0:
        raise SystemExit(f"{arguments[0]} failed ({done.returncode}):\n{done.stderr}")


def steps() -> None:
    """The pipeline end to end on the versioned sample, then the two published artefacts.

    The first step is the product: extract, transform, load, metrics, cleanup, five steps and
    a real database at the end. It runs on the Fakeddit sample committed under
    ``data/samples/``, whose twenty-four rows are the only input of this repository that does
    not change underneath it. It still reaches the network, to download the images those rows
    point at — a pipeline built around « no image on disk, no publication » has nothing to
    prove without that download.
    """
    with tempfile.TemporaryDirectory(prefix="multimodal-smoke-") as scratch:
        corpus = Path(scratch)
        _run(
            str(SCRIPTS_DIR / "run_etl.py"),
            environment={
                "MULTIMODAL_ETL_DATA_DIR": str(corpus),
                "MULTIMODAL_ETL_SOURCES": SMOKE_SOURCE,
                "MULTIMODAL_ETL_DB_URL": f"sqlite:///{(corpus / 'smoke.db').as_posix()}",
            },
        )
        # The sample ships its images: a run that kept nothing did not exercise the rule the
        # whole pipeline is built around, and would otherwise report a clean pass.
        datasets = sorted((corpus / "processed").glob("publications_*.parquet"))
        if not datasets:
            raise SystemExit("the run produced no dataset: nothing downstream is worth writing")

    # The schema the documents show, derived from the code. `--no-render` because mermaid-cli
    # draws a different PNG from one version to the next, and what is compared here is text.
    _run(str(SCRIPTS_DIR / "build_schema_diagram.py"), "--no-render")
    # The published report, rendered from the measures of the published run.
    _run(str(SCRIPTS_DIR / "quality_report.py"))


# --- What the evidence records ----------------------------------------------


def _git(*arguments: str) -> str:
    done = subprocess.run(
        ["git", *arguments], cwd=ROOT_DIR, capture_output=True, text=True, check=False
    )
    return done.stdout.strip()


def tool_versions() -> dict[str, str]:
    versions = {"python": platform.python_version()}
    for name in TOOLS:
        try:
            versions[name] = version(name)
        except PackageNotFoundError:
            versions[name] = "not installed"
    for binary, arguments in (("uv", ("--version",)), ("docker", ("--version",))):
        if shutil.which(binary):
            done = subprocess.run([binary, *arguments], capture_output=True, text=True, check=False)
            versions[binary] = done.stdout.strip() or "unknown"
    return versions


def reproduced() -> list[str]:
    """The key outputs the run did NOT reproduce: missing, untracked, or changed."""
    problems: list[str] = []
    for rel in KEY_OUTPUT:
        if not (ROOT_DIR / rel).exists():
            problems.append(f"{rel} — not produced")
            continue
        if not _git("ls-files", "--error-unmatch", rel):
            problems.append(f"{rel} — produced but not tracked by git")
            continue
        if _git("status", "--porcelain", "--", rel):
            problems.append(f"{rel} — differs from the committed version")
    return problems


def main() -> int:
    started = time.monotonic()
    steps()
    duration = round(time.monotonic() - started, 1)

    differences = reproduced()
    if differences:
        print("the run did not reproduce what is published:", file=sys.stderr)
        for line in differences:
            print(f"  {line}", file=sys.stderr)
        print(f"{EVIDENCE} not written", file=sys.stderr)
        return 1

    evidence = {
        "command": COMMAND,
        "ran_at": datetime.now(tz=UTC).date().isoformat(),
        "git_revision": _git("rev-parse", "HEAD"),
        "tool_versions": tool_versions(),
        "duration_seconds": duration,
        "key_output": list(KEY_OUTPUT),
        # Null, and said so: the workflows of this repository are frozen to a manual trigger,
        # so there is no run to point at. A missing key would read as an oversight.
        "workflow_run_url": None,
    }
    target = ROOT_DIR / EVIDENCE
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        json.dumps(evidence, indent=2, ensure_ascii=False) + "\n", encoding="utf-8", newline=""
    )
    print(f"{EVIDENCE} written — {duration}s, {len(KEY_OUTPUT)} output(s) reproduced")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
