erDiagram
    SOURCE ||--o{ PUBLICATION : publie
    PUBLICATION ||--|| CONTENU_TEXTE : porte
    PUBLICATION ||--|| CONTENU_IMAGE : associe
    PUBLICATION ||--o| LABEL : annote

    PUBLICATION {
        string id PK "KEY"
        string source_id FK "KEY"
        string domain  "METADATA"
        string url  "METADATA"
        string language  "METADATA"
        datetime published_at  "METADATA"
        datetime ingested_at  "METADATA"
    }

    SOURCE {
        string source_id PK "KEY"
        string source  "METADATA"
        string source_type  "METADATA"
        string access_method  "METADATA"
    }

    CONTENU_TEXTE {
        string id PK "KEY"
        string title  "NLP"
        string text  "NLP"
        int text_length  "METADATA"
    }

    CONTENU_IMAGE {
        string id PK "KEY"
        string image_url  "VISION"
        string image_path  "VISION"
        string image_source  "METADATA"
        bool has_image  "VISION"
    }

    LABEL {
        string id PK "KEY"
        string label  "TARGET"
        string label_source  "METADATA"
    }
